// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseProto.proto

package org.vite.dex.api.client.domain.event;

public final class DexProto {
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_protocol_DexProtocol_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_protocol_DexProtocol_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\017BaseProto.proto\022\010protocol\"f\n\013DexProtoc" +
                        "ol\022\021\n\tclient_id\030\001 \001(\t\022\016\n\006topics\030\002 \001(\t\022\017\n" +
                        "\007op_type\030\003 \001(\t\022\017\n\007message\030\004 \001(\014\022\022\n\nerror" +
                        "_code\030\005 \001(\005B+\n\037org.vite.data.dex.bean.pr" +
                        "otocolB\010DexProtob\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_protocol_DexProtocol_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_protocol_DexProtocol_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_protocol_DexProtocol_descriptor,
                new String[]{"ClientId", "Topics", "OpType", "Message", "ErrorCode",});
    }

    private DexProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface DexProtocolOrBuilder extends
            // @@protoc_insertion_point(interface_extends:protocol.DexProtocol)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string client_id = 1;</code>
         *
         * <pre>
         * Identify a single client
         * </pre>
         */
        String getClientId();

        /**
         * <code>optional string client_id = 1;</code>
         *
         * <pre>
         * Identify a single client
         * </pre>
         */
        com.google.protobuf.ByteString
        getClientIdBytes();

        /**
         * <code>optional string topics = 2;</code>
         *
         * <pre>
         * order.$address.latest|market.$pair_symbol.[kline|buy|sell|detail|details|trade].$param
         * </pre>
         */
        String getTopics();

        /**
         * <code>optional string topics = 2;</code>
         *
         * <pre>
         * order.$address.latest|market.$pair_symbol.[kline|buy|sell|detail|details|trade].$param
         * </pre>
         */
        com.google.protobuf.ByteString
        getTopicsBytes();

        /**
         * <code>optional string op_type = 3;</code>
         *
         * <pre>
         *  sub,un_sub,ping,pong,push
         * </pre>
         */
        String getOpType();

        /**
         * <code>optional string op_type = 3;</code>
         *
         * <pre>
         *  sub,un_sub,ping,pong,push
         * </pre>
         */
        com.google.protobuf.ByteString
        getOpTypeBytes();

        /**
         * <code>optional bytes message = 4;</code>
         *
         * <pre>
         * proto数据
         * </pre>
         */
        com.google.protobuf.ByteString getMessage();

        /**
         * <code>optional int32 error_code = 5;</code>
         *
         * <pre>
         * 错误编码
         * </pre>
         */
        int getErrorCode();
    }

    /**
     * Protobuf type {@code protocol.DexProtocol}
     */
    public static final class DexProtocol extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:protocol.DexProtocol)
            DexProtocolOrBuilder {
        public static final int CLIENT_ID_FIELD_NUMBER = 1;
        public static final int TOPICS_FIELD_NUMBER = 2;
        public static final int OP_TYPE_FIELD_NUMBER = 3;
        public static final int MESSAGE_FIELD_NUMBER = 4;
        public static final int ERROR_CODE_FIELD_NUMBER = 5;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:protocol.DexProtocol)
        private static final DexProtocol DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<DexProtocol>
                PARSER = new com.google.protobuf.AbstractParser<DexProtocol>() {
            public DexProtocol parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                try {
                    return new DexProtocol(input, extensionRegistry);
                } catch (RuntimeException e) {
                    if (e.getCause() instanceof
                            com.google.protobuf.InvalidProtocolBufferException) {
                        throw (com.google.protobuf.InvalidProtocolBufferException)
                                e.getCause();
                    }
                    throw e;
                }
            }
        };

        static {
            DEFAULT_INSTANCE = new DexProtocol();
        }

        private volatile Object clientId_;
        private volatile Object topics_;
        private volatile Object opType_;
        private com.google.protobuf.ByteString message_;
        private int errorCode_;
        private byte memoizedIsInitialized = -1;
        // Use DexProtocol.newBuilder() to construct.
        private DexProtocol(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private DexProtocol() {
            clientId_ = "";
            topics_ = "";
            opType_ = "";
            message_ = com.google.protobuf.ByteString.EMPTY;
            errorCode_ = 0;
        }

        private DexProtocol(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            clientId_ = s;
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            topics_ = s;
                            break;
                        }
                        case 26: {
                            String s = input.readStringRequireUtf8();

                            opType_ = s;
                            break;
                        }
                        case 34: {

                            message_ = input.readBytes();
                            break;
                        }
                        case 40: {

                            errorCode_ = input.readInt32();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
                throw new RuntimeException(
                        new com.google.protobuf.InvalidProtocolBufferException(
                                e.getMessage()).setUnfinishedMessage(this));
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return DexProto.internal_static_protocol_DexProtocol_descriptor;
        }

        public static DexProtocol parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static DexProtocol parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static DexProtocol parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static DexProtocol parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static DexProtocol parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static DexProtocol parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static DexProtocol parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static DexProtocol parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static DexProtocol parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static DexProtocol parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(DexProtocol prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static DexProtocol getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<DexProtocol> parser() {
            return PARSER;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return DexProto.internal_static_protocol_DexProtocol_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            DexProtocol.class, Builder.class);
        }

        /**
         * <code>optional string client_id = 1;</code>
         *
         * <pre>
         * Identify a single client
         * </pre>
         */
        public String getClientId() {
            Object ref = clientId_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                clientId_ = s;
                return s;
            }
        }

        /**
         * <code>optional string client_id = 1;</code>
         *
         * <pre>
         * Identify a single client
         * </pre>
         */
        public com.google.protobuf.ByteString
        getClientIdBytes() {
            Object ref = clientId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                clientId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional string topics = 2;</code>
         *
         * <pre>
         * order.$address.latest|market.$pair_symbol.[kline|buy|sell|detail|details|trade].$param
         * </pre>
         */
        public String getTopics() {
            Object ref = topics_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                topics_ = s;
                return s;
            }
        }

        /**
         * <code>optional string topics = 2;</code>
         *
         * <pre>
         * order.$address.latest|market.$pair_symbol.[kline|buy|sell|detail|details|trade].$param
         * </pre>
         */
        public com.google.protobuf.ByteString
        getTopicsBytes() {
            Object ref = topics_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                topics_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional string op_type = 3;</code>
         *
         * <pre>
         *  sub,un_sub,ping,pong,push
         * </pre>
         */
        public String getOpType() {
            Object ref = opType_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                opType_ = s;
                return s;
            }
        }

        /**
         * <code>optional string op_type = 3;</code>
         *
         * <pre>
         *  sub,un_sub,ping,pong,push
         * </pre>
         */
        public com.google.protobuf.ByteString
        getOpTypeBytes() {
            Object ref = opType_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                opType_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional bytes message = 4;</code>
         *
         * <pre>
         * proto数据
         * </pre>
         */
        public com.google.protobuf.ByteString getMessage() {
            return message_;
        }

        /**
         * <code>optional int32 error_code = 5;</code>
         *
         * <pre>
         * 错误编码
         * </pre>
         */
        public int getErrorCode() {
            return errorCode_;
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getClientIdBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessage.writeString(output, 1, clientId_);
            }
            if (!getTopicsBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessage.writeString(output, 2, topics_);
            }
            if (!getOpTypeBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessage.writeString(output, 3, opType_);
            }
            if (!message_.isEmpty()) {
                output.writeBytes(4, message_);
            }
            if (errorCode_ != 0) {
                output.writeInt32(5, errorCode_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getClientIdBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(1, clientId_);
            }
            if (!getTopicsBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(2, topics_);
            }
            if (!getOpTypeBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(3, opType_);
            }
            if (!message_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(4, message_);
            }
            if (errorCode_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(5, errorCode_);
            }
            memoizedSize = size;
            return size;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<DexProtocol> getParserForType() {
            return PARSER;
        }

        public DexProtocol getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code protocol.DexProtocol}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:protocol.DexProtocol)
                DexProtocolOrBuilder {
            private Object clientId_ = "";
            private Object topics_ = "";
            private Object opType_ = "";
            private com.google.protobuf.ByteString message_ = com.google.protobuf.ByteString.EMPTY;
            private int errorCode_;

            // Construct using org.vite.data.dex.bean.protocol.DexProto.DexProtocol.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return DexProto.internal_static_protocol_DexProtocol_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return DexProto.internal_static_protocol_DexProtocol_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                DexProtocol.class, Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                clientId_ = "";

                topics_ = "";

                opType_ = "";

                message_ = com.google.protobuf.ByteString.EMPTY;

                errorCode_ = 0;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return DexProto.internal_static_protocol_DexProtocol_descriptor;
            }

            public DexProtocol getDefaultInstanceForType() {
                return DexProtocol.getDefaultInstance();
            }

            public DexProtocol build() {
                DexProtocol result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public DexProtocol buildPartial() {
                DexProtocol result = new DexProtocol(this);
                result.clientId_ = clientId_;
                result.topics_ = topics_;
                result.opType_ = opType_;
                result.message_ = message_;
                result.errorCode_ = errorCode_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof DexProtocol) {
                    return mergeFrom((DexProtocol) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(DexProtocol other) {
                if (other == DexProtocol.getDefaultInstance()) return this;
                if (!other.getClientId().isEmpty()) {
                    clientId_ = other.clientId_;
                    onChanged();
                }
                if (!other.getTopics().isEmpty()) {
                    topics_ = other.topics_;
                    onChanged();
                }
                if (!other.getOpType().isEmpty()) {
                    opType_ = other.opType_;
                    onChanged();
                }
                if (other.getMessage() != com.google.protobuf.ByteString.EMPTY) {
                    setMessage(other.getMessage());
                }
                if (other.getErrorCode() != 0) {
                    setErrorCode(other.getErrorCode());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                DexProtocol parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (DexProtocol) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>optional string client_id = 1;</code>
             *
             * <pre>
             * Identify a single client
             * </pre>
             */
            public String getClientId() {
                Object ref = clientId_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    clientId_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string client_id = 1;</code>
             *
             * <pre>
             * Identify a single client
             * </pre>
             */
            public Builder setClientId(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                clientId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string client_id = 1;</code>
             *
             * <pre>
             * Identify a single client
             * </pre>
             */
            public com.google.protobuf.ByteString
            getClientIdBytes() {
                Object ref = clientId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    clientId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string client_id = 1;</code>
             *
             * <pre>
             * Identify a single client
             * </pre>
             */
            public Builder setClientIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                clientId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string client_id = 1;</code>
             *
             * <pre>
             * Identify a single client
             * </pre>
             */
            public Builder clearClientId() {

                clientId_ = getDefaultInstance().getClientId();
                onChanged();
                return this;
            }

            /**
             * <code>optional string topics = 2;</code>
             *
             * <pre>
             * order.$address.latest|market.$pair_symbol.[kline|buy|sell|detail|details|trade].$param
             * </pre>
             */
            public String getTopics() {
                Object ref = topics_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    topics_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string topics = 2;</code>
             *
             * <pre>
             * order.$address.latest|market.$pair_symbol.[kline|buy|sell|detail|details|trade].$param
             * </pre>
             */
            public Builder setTopics(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                topics_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string topics = 2;</code>
             *
             * <pre>
             * order.$address.latest|market.$pair_symbol.[kline|buy|sell|detail|details|trade].$param
             * </pre>
             */
            public com.google.protobuf.ByteString
            getTopicsBytes() {
                Object ref = topics_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    topics_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string topics = 2;</code>
             *
             * <pre>
             * order.$address.latest|market.$pair_symbol.[kline|buy|sell|detail|details|trade].$param
             * </pre>
             */
            public Builder setTopicsBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                topics_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string topics = 2;</code>
             *
             * <pre>
             * order.$address.latest|market.$pair_symbol.[kline|buy|sell|detail|details|trade].$param
             * </pre>
             */
            public Builder clearTopics() {

                topics_ = getDefaultInstance().getTopics();
                onChanged();
                return this;
            }

            /**
             * <code>optional string op_type = 3;</code>
             *
             * <pre>
             *  sub,un_sub,ping,pong,push
             * </pre>
             */
            public String getOpType() {
                Object ref = opType_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    opType_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string op_type = 3;</code>
             *
             * <pre>
             *  sub,un_sub,ping,pong,push
             * </pre>
             */
            public Builder setOpType(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                opType_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string op_type = 3;</code>
             *
             * <pre>
             *  sub,un_sub,ping,pong,push
             * </pre>
             */
            public com.google.protobuf.ByteString
            getOpTypeBytes() {
                Object ref = opType_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    opType_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string op_type = 3;</code>
             *
             * <pre>
             *  sub,un_sub,ping,pong,push
             * </pre>
             */
            public Builder setOpTypeBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                opType_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional string op_type = 3;</code>
             *
             * <pre>
             *  sub,un_sub,ping,pong,push
             * </pre>
             */
            public Builder clearOpType() {

                opType_ = getDefaultInstance().getOpType();
                onChanged();
                return this;
            }

            /**
             * <code>optional bytes message = 4;</code>
             *
             * <pre>
             * proto数据
             * </pre>
             */
            public com.google.protobuf.ByteString getMessage() {
                return message_;
            }

            /**
             * <code>optional bytes message = 4;</code>
             *
             * <pre>
             * proto数据
             * </pre>
             */
            public Builder setMessage(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                message_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional bytes message = 4;</code>
             *
             * <pre>
             * proto数据
             * </pre>
             */
            public Builder clearMessage() {

                message_ = getDefaultInstance().getMessage();
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 error_code = 5;</code>
             *
             * <pre>
             * 错误编码
             * </pre>
             */
            public int getErrorCode() {
                return errorCode_;
            }

            /**
             * <code>optional int32 error_code = 5;</code>
             *
             * <pre>
             * 错误编码
             * </pre>
             */
            public Builder setErrorCode(int value) {

                errorCode_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 error_code = 5;</code>
             *
             * <pre>
             * 错误编码
             * </pre>
             */
            public Builder clearErrorCode() {

                errorCode_ = 0;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:protocol.DexProtocol)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
